@TOKEN=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJJZCI6IjVmZTkwMTk5MmQ0OWY4NDE0NDMwZjJlMCJ9LCJpYXQiOjE2MDkxMjI2MDcsImV4cCI6MTYwOTEyNjIwN30.jF36Gcp2jChciZIQdhoqZVjd-hYJwJxWRD3bYokkF_Y
@BASE_URL=http://localhost:{{$dotenv PORT}}/api/v1
@EVENT_ID=5fe94a5fa274cc19ac12cb20

##########  AUTHORIZED  ############

### GET all
GET {{BASE_URL}}/events
Authorization: {{TOKEN}}

### POST
POST {{BASE_URL}}/events
Authorization: {{TOKEN}}
content-type: application/json

{
    "title": "Zybr title",
    "description": "zybr01 desc",
    "date": "2020-10-23"
}

### GET by :id
GET {{BASE_URL}}/events/{{EVENT_ID}}
Authorization: {{TOKEN}}


### PUT by :id
PUT {{BASE_URL}}/events/{{EVENT_ID}}
Authorization: {{TOKEN}}
content-type: application/json

{
    "title": "Zybr titlePUT",
    "description": "zybr02 desc",
    "date": "2020-10-24"
}

### DELETE by :id
DELETE {{BASE_URL}}/events/{{EVENT_ID}}
Authorization: {{TOKEN}}


##########  NOT AUTHORIZED  ############

#### Get ALL
GET {{BASE_URL}}/events

### POST
POST {{BASE_URL}}/events
content-type: application/json

{
    "title": "Zybr title",
    "description": "zybr01 desc",
    "date": "2020-10-23"
}

### GET by :id
GET {{BASE_URL}}/events/{{EVENT_ID}}

### PUT by :id
PUT {{BASE_URL}}/events/{{EVENT_ID}}
content-type: application/json

{
    "title": "Zybr title",
    "description": "zybr01 desc",
    "date": "2020-10-23"
}
 
### DELETE by :id
DELETE {{BASE_URL}}/events/{{EVENT_ID}}
 